#!/bin/bash

echo "🔄 Database Migration Guide"
echo "=========================="
echo ""
echo "Your current database has the old schema. Follow these steps to migrate:"
echo ""
echo "📋 Migration Steps:"
echo ""
echo "1. 🗂️  Open your Supabase Dashboard"
echo "   - Go to https://supabase.com/dashboard"
echo "   - Select your project"
echo ""
echo "2. 📝 Open SQL Editor"
echo "   - Click on 'SQL Editor' in the left sidebar"
echo "   - Click 'New Query'"
echo ""
echo "3. 📋 Copy Migration Script"
echo "   - Copy the contents of: supabase/migrations/002_update_schema.sql"
echo "   - Paste it into the SQL Editor"
echo ""
echo "4. ▶️  Run the Migration"
echo "   - Click 'Run' to execute the migration"
echo "   - Wait for completion message"
echo ""
echo "5. 🌱 Seed Sample Data (Optional)"
echo "   - Start your development server: npm run dev"
echo "   - Navigate to /protected/dash"
echo "   - Sign in with your account"
echo "   - Open browser console and run:"
echo "     fetch('/api/seed', { method: 'POST' })"
echo ""
echo "🔍 What the migration does:"
echo "   ✅ Adds new columns to existing tables (tests, questions)"
echo "   ✅ Creates new tables (user_test_attempts, user_question_responses)"
echo "   ✅ Adds proper indexes for performance"
echo "   ✅ Sets up Row Level Security policies"
echo "   ✅ Preserves your existing data"
echo ""
echo "⚠️  Important Notes:"
echo "   - This migration is safe and preserves existing data"
echo "   - Backup your database before running if you have important data"
echo "   - The migration adds new features without breaking existing functionality"
echo ""
echo "🚀 After migration, you'll have:"
echo "   - Dynamic user scoring system"
echo "   - Time-based test availability"
echo "   - Individual test attempt tracking"
echo "   - Detailed question response recording"
echo "   - Enhanced test interface"
echo ""
echo "Ready to migrate! 🎉"
